In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
t = tf.range(0., 10.)
print(t)
t = t * 2
print(t)
t = t + 1
print(t)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)
tf.Tensor([ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.], shape=(10,), dtype=float32)
tf.Tensor([ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.], shape=(10,), dtype=float32)


In [4]:
@tf.function
def my_func(t):
    print("new graph created", t.dtype, t.shape)
    t = t * 2
    print(t)
    t = t + 1
    print(t)
    return t

t = tf.range(0., 10.)
my_func(t)

new graph created <dtype: 'float32'> (10,)
Tensor("mul:0", shape=(10,), dtype=float32)
Tensor("add:0", shape=(10,), dtype=float32)


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)>

In [5]:
print(t.numpy())

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [6]:
my_func(tf.range(10., 20.))

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([21., 23., 25., 27., 29., 31., 33., 35., 37., 39.], dtype=float32)>

In [7]:
my_func(tf.range(10., 21.))
print("---")
my_func(tf.range(10, 20, dtype=tf.int32))

new graph created <dtype: 'float32'> (11,)
Tensor("mul:0", shape=(11,), dtype=float32)
Tensor("add:0", shape=(11,), dtype=float32)
---
new graph created <dtype: 'int32'> (10,)
Tensor("mul:0", shape=(10,), dtype=int32)
Tensor("add:0", shape=(10,), dtype=int32)


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39], dtype=int32)>